import { TGame } from '../types/TGame'

export const Games: TGame[] = [
  {
    id: 0,
    name: 'Bad Dog',
    provider: 'Tencent',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/237/300/300',
    type: 'casino',
  },
  {
    id: 1,
    name: 'Good Dog',
    provider: 'Steam',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/239/300/300',
    type: 'casino',
  },
  {
    id: 2,
    name: 'Brave Dog',
    provider: 'Epic',
    category: 'Live',
    imageUrl: 'https://picsum.photos/id/236/300/300',
    type: 'casino',
  },
  {
    id: 3,
    name: 'Lazy Dog',
    provider: 'Epic',
    category: 'New',
    imageUrl: 'https://picsum.photos/id/255/300/300',
    type: 'casino',
  },
  {
    id: 4,
    name: 'Crocodile Farm',
    provider: 'Bang',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/231/300/300',
    type: 'casino',
  },
  {
    id: 5,
    name: 'Dragon ball',
    provider: 'Epic',
    category: 'Jackpot',
    imageUrl: 'https://picsum.photos/id/215/300/300',
    type: 'casino',
  },
  {
    id: 6,
    name: 'Scavenger',
    provider: 'Epic',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/225/300/300',
    type: 'casino',
  },
  {
    id: 7,
    name: 'White Tiger',
    provider: 'Bang',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/232/300/300',
    type: 'casino',
  },
  {
    id: 8,
    name: 'Saitama',
    provider: 'Epic',
    category: 'Jackpot',
    imageUrl: 'https://picsum.photos/id/216/300/300',
    type: 'casino',
  },
  {
    id: 9,
    name: 'Hunters',
    provider: 'Epic',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/223/300/300',
    type: 'casino',
  },
  {
    id: 10,
    name: 'Soccer',
    provider: 'Tence',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/120/300/300',
    type: 'sports',
  },
  {
    id: 11,
    name: 'Basketball',
    provider: 'Steam',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/121/300/300',
    type: 'sports',
  },
  {
    id: 12,
    name: 'Volleyball',
    provider: 'Epic',
    category: 'Live',
    imageUrl: 'https://picsum.photos/id/122/300/300',
    type: 'sports',
  },
  {
    id: 13,
    name: 'Tennis',
    provider: 'Epic',
    category: 'New',
    imageUrl: 'https://picsum.photos/id/123/300/300',
    type: 'sports',
  },
  {
    id: 14,
    name: 'MMA',
    provider: 'Bang',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/124/300/300',
    type: 'sports',
  },
  {
    id: 15,
    name: 'Golf',
    provider: 'Epic',
    category: 'Jackpot',
    imageUrl: 'https://picsum.photos/id/125/300/300',
    type: 'sports',
  },
  {
    id: 16,
    name: 'Horse',
    provider: 'Epic',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/126/300/300',
    type: 'casino',
  },
  {
    id: 17,
    name: 'Eagle',
    provider: 'Bang',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/127/300/300',
    type: 'casino',
  },
  {
    id: 18,
    name: 'Bears',
    provider: 'Epic',
    category: 'Jackpot',
    imageUrl: 'https://picsum.photos/id/128/300/300',
    type: 'casino',
  },
  {
    id: 19,
    name: 'Ted',
    provider: 'Epic',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/129/300/300',
    type: 'casino',
  },
]
