import { TGame } from '../types/TGame'

export const Games: TGame[] = [
  {
    id: 0,
    name: 'Bad Dog',
    provider: 'Tence',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/237/300/300',
    type: 'casino',
  },
  {
    id: 1,
    name: 'Good Dog',
    provider: 'Steam',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/239/300/300',
    type: 'casino',
  },
  {
    id: 2,
    name: 'Brave Dog',
    provider: 'Epic',
    category: 'Live',
    imageUrl: 'https://picsum.photos/id/236/300/300',
    type: 'casino',
  },
  {
    id: 3,
    name: 'Brave Dog',
    provider: 'Epic',
    category: 'New',
    imageUrl: 'https://picsum.photos/id/255/300/300',
    type: 'casino',
  },
  {
    id: 4,
    name: 'Crocodile Farm',
    provider: 'Bang',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/231/300/300',
    type: 'casino',
  },
  {
    id: 5,
    name: 'Dragon ball',
    provider: 'Epic',
    category: 'Jackpot',
    imageUrl: 'https://picsum.photos/id/215/300/300',
    type: 'casino',
  },
  {
    id: 6,
    name: 'Scavenger',
    provider: 'Epic',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/225/300/300',
    type: 'casino',
  },
  {
    id: 7,
    name: 'White Tiger',
    provider: 'Bang',
    category: 'Slots',
    imageUrl: 'https://picsum.photos/id/232/300/300',
    type: 'casino',
  },
  {
    id: 8,
    name: 'Saitama',
    provider: 'Epic',
    category: 'Jackpot',
    imageUrl: 'https://picsum.photos/id/216/300/300',
    type: 'casino',
  },
  {
    id: 9,
    name: 'Hunters',
    provider: 'Epic',
    category: 'Start',
    imageUrl: 'https://picsum.photos/id/223/300/300',
    type: 'casino',
  },
]
